FROM 				hudak/oracle-java7
MAINTAINER 	Saad Farooq <sa@dfarooq.com>
ADD 				http://download-cf.jetbrains.com/teamcity/TeamCity-8.1.2.tar.gz /opt
EXPOSE      8111
CMD 				["/opt/TeamCity/bin/teamcity-server.sh","run"]