web:
  build: .
  ports: 
    - "8111:8111"
  volumes:
    - BuildServer/:/BuildServer
  links:
    - db
db:
  image: mysql:5.7.6
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: somepass
    MYSQL_DATABASE: teamcity
    MYSQL_USER: admin
    MYSQL_PASSWORD: nopass
